# Generated by Django 6.0.3 on 2026-03-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggerprofile',
            name='price_long',
        ),
        migrations.RemoveField(
            model_name='bloggerprofile',
            name='price_short',
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='price_end',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Интеграция в конце'),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='price_middle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Интеграция в середине'),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='price_shorts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за Shorts'),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='price_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Интеграция в начале'),
        ),
        migrations.AlterField(
            model_name='bloggerprofile',
            name='categories',
            field=models.CharField(max_length=500, verbose_name='Тематики'),
        ),
    ]
