# Generated by Django 6.0.3 on 2026-03-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_bloggerprofile_price_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='subscribers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Подписчиков'),
        ),
    ]
