# Generated by Django 6.0.3 on 2026-04-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='median_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Медиана просмотров (Long)'),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='median_views_shorts',
            field=models.PositiveIntegerField(default=0, verbose_name='Медиана просмотров (Shorts)'),
        ),
    ]
