# Generated by Django 6.0.3 on 2026-04-09 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bloggerprofile_median_views_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объявление товара', 'verbose_name_plural': 'Объявления товаров'},
        ),
        migrations.AddField(
            model_name='productad',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото товара'),
        ),
        migrations.AddField(
            model_name='productad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Опубликовать в маркетплейсе'),
        ),
        migrations.AddField(
            model_name='productad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productad',
            name='link',
            field=models.URLField(verbose_name='Ссылка на товар (WB/Ozon)'),
        ),
        migrations.CreateModel(
            name='AdvertProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка на WB/Ozon')),
                ('description', models.TextField(blank=True, help_text='Что обязательно сказать в ролике?', verbose_name='ТЗ для блогера')),
                ('image_url', models.URLField(blank=True, help_text='Ссылка на диск или фото товара', verbose_name='Ссылка на фото/материалы')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
