# Generated by Django 6.0.3 on 2026-04-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_productad_options_productad_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
