# Generated by Django 6.0.3 on 2026-04-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bloggerprofile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productad',
            name='link',
        ),
        migrations.AddField(
            model_name='productad',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на WB/Ozon/Сайт'),
        ),
        migrations.AddField(
            model_name='productad',
            name='link_ozon',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на Ozon'),
        ),
        migrations.AddField(
            model_name='productad',
            name='link_site',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на сайт/другое'),
        ),
        migrations.AddField(
            model_name='productad',
            name='link_wb',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на Wildberries'),
        ),
    ]
