# Generated by Django 6.0.3 on 2026-04-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_productad_link_productad_external_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerprofile',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Баннер канала'),
        ),
        migrations.AlterField(
            model_name='advertproduct',
            name='description',
            field=models.TextField(blank=True, verbose_name='ТЗ для блогера'),
        ),
        migrations.AlterField(
            model_name='advertproduct',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на фото/материалы'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='category',
            field=models.CharField(choices=[('tech', 'Технологии и IT'), ('beauty', 'Красота и косметика'), ('games', 'Гейминг'), ('finance', 'Финансы и бизнес'), ('lifestyle', 'Лайфстайл/Влоги'), ('education', 'Образование'), ('auto', 'Автомобили'), ('food', 'Кулинария')], max_length=100, verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фото товара'),
        ),
    ]
