# Generated by Django 6.0.3 on 2026-04-15 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bloggerprofile_banner_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productad',
            name='category',
            field=models.CharField(choices=[('tech', 'Технологии и IT'), ('beauty', 'Красота и косметика'), ('games', 'Гейминг'), ('finance', 'Финансы и бизнес'), ('lifestyle', 'Лайфстайл/Влоги'), ('education', 'Образование'), ('auto', 'Автомобили'), ('food', 'Кулинария'), ('fashion', 'Мода')], max_length=100, verbose_name='Категория товара'),
        ),
        migrations.CreateModel(
            name='AdContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен (Заморожено)'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adv_contracts', to=settings.AUTH_USER_MODEL)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogger_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=50, verbose_name='Формат')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('review', 'На утверждении'), ('correction', 'На доработке'), ('approved', 'Утвержден'), ('released', 'Выпущен')], default='in_progress', max_length=20)),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('time_start', models.CharField(blank=True, max_length=10, verbose_name='Начало рекламы')),
                ('time_end', models.CharField(blank=True, max_length=10, verbose_name='Конец рекламы')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.adcontract')),
            ],
            options={
                'verbose_name': 'Ролик',
                'verbose_name_plural': 'Ролики',
            },
        ),
    ]
