# Generated by Django 6.0.3 on 2026-04-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_productad_category_adcontract_videoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='productad',
            name='category',
            field=models.CharField(choices=[('education', 'Образование и наука'), ('tech', 'Технологии и гаджеты'), ('diy', 'Дом, ремонт и рукоделие'), ('lifestyle', 'Лайфстайл и блогинг'), ('business', 'Бизнес и финансы'), ('entertainment', 'Развлечения и поп-культура'), ('sport', 'Спорт и здоровье'), ('auto', 'Авто и техника'), ('food', 'Еда и кулинария'), ('art', 'Искусство и культура')], max_length=100, verbose_name='Категория товара'),
        ),
    ]
