# Generated by Django 6.0.3 on 2026-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_supportticket_alter_productad_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='category',
            field=models.CharField(choices=[('education', 'Образование и наука'), ('tech', 'Технологии и гаджеты'), ('diy', 'Дом, ремонт и рукоделие'), ('lifestyle', 'Лайфстайл и блогинг'), ('business', 'Бизнес и финансы'), ('entertainment', 'Развлечения и поп-культура'), ('sport', 'Спорт и здоровье'), ('auto', 'Авто и техника'), ('food', 'Еда и кулинария'), ('art', 'Искусство и культура')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productad',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
