# Generated by Django 6.0.3 on 2026-04-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_productad_image_alter_productad_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productad',
            name='external_url',
        ),
        migrations.AddField(
            model_name='productad',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бюджет/Цена'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='category',
            field=models.CharField(max_length=500, verbose_name='Категории (через запятую)'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Файл фото'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='link_ozon',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ozon'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='link_site',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Сайт/Другое'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='link_wb',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Wildberries'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='AdvertProduct',
        ),
    ]
